[tool.poetry]
name = "python"
version = "0.1.0"
description = ""
authors = ["Daniel Lee <daniel@bayesianops.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
cmdstanpy = "^1.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
